=== beerose/diversity.lol/public/schema/v1.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Conference",
	"description": "A conference",
	"type": "object",
	"additionalProperties": false,
	"required": ["name", "description", "startDate", "tags", "location", "url", "speakers"],
	"properties": {
		"$schema": {
			"type": "string"
		},
		"name": {
			"description": "The name of the conference",
			"type": "string"
		},
		"description": {
			"description": "More information about the conference",
			"type": "string"
		},
		"startDate": {
			"description": "The start date of the conference (YYYY-MM-DD)",
			"type": "string"
		},
		"cfp": {
			"description": "The CFP open and close dates of the conference (YYYY-MM-DD)",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"open": {
					"description": "The CFP open date of the conference (YYYY-MM-DD)",
					"type": "string"
				},
				"close": {
					"description": "The CFP close date of the conference (YYYY-MM-DD)",
					"type": "string"
				},
				"url": {
					"description": "The CFP URL of the conference",
					"type": "string"
				}
			}
		},
		"status": {
			"description": "The status of the conference",
			"type": "string",
			"enum": ["cfp open", "cfp closed"]
		},
		"tags": {
			"description": "The tags of the conference",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"location": {
			"description": "The location of the conference",
			"type": "string"
		},
		"url": {
			"description": "The URL of the conference",
			"type": "string"
		},
		"social": {
			"description": "The social media of the conference",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"twitter": {
					"description": "The Twitter handle of the conference",
					"type": "string"
				}
			}
		},
		"organizer": {
			"description": "The organizer of the conference",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"description": "The name of the organizer",
					"type": "string"
				},
				"url": {
					"description": "The URL of the organizer",
					"type": "string"
				},
				"forProfit": {
					"description": "Whether the organizer is for-profit",
					"type": "boolean"
				}
			}
		},
		"size": {
			"description": "The size of the conference",
			"type": "string"
		},
		"speakers": {
			"description": "The speakers of the conference",
			"type": "object",
			"additionalProperties": false,
			"required": ["total", "womenAndNonBinary"],
			"properties": {
				"total": {
					"description": "The total number of speakers",
					"type": "number"
				},
				"womenAndNonBinary": {
					"description": "The number of women and non-binary speakers",
					"type": "number"
				},
				"womenAndNonBinaryMain": {
					"description": "The number of women and non-binary speakers on the main track (if there is one)",
					"type": "number"
				}
			}
		}
	}
}

=== beerose/diversity.lol/data/conferences/testjssummit.json
{
  "$schema": "../../public/schema/v1.json",
  "name": "Test JS Summit 2023",
  "description": "TestJS Summit is a 2-day conference discussing all things JS testing. The event is going to gather QAs and developers in-person.",
  "startDate": "2023-12-07",
  "location": "Hybrid",
  "url": "https://testjssummit.com/",
  "tags": ["JavaScript", "Testing"],
  "speakers": {
    "total": 31,
    "womenAndNonBinary": 10
  },
  "organizer": {
    "name": "GitNation"
  }
}

=== beerose/diversity.lol/data/conferences/reactberlin.json
{
  "$schema": "../../public/schema/v1.json",
  "name": "React Day Berlin 2023",
  "description": "React Day Berlin is your gateway to new opportunities and exciting collaboration on stellar tech. Attend in-depth talks, supercharge your hard and soft skills with career-boosting workshops, and connect with React enthusiasts.",
  "startDate": "2023-12-08",
  "location": "Hybrid",
  "url": "https://reactday.berlin/",
  "tags": [
    "JavaScript",
    "React",
    "React Native"
  ],
  "speakers": {
    "total": 56,
    "womenAndNonBinary": 5
  },
  "organizer": {
    "name": "GitNation"
  }
}

=== beerose/diversity.lol/data/conferences/bejs.json
{
  "$schema": "../../public/schema/v1.json",
  "name": "BeJS 2023",
  "description": "A family-like, community-run JavaScript Conference!",
  "startDate": "2023-05-12",
  "location": "Brussels, Belgium",
  "url": "https://www.bejs.io/conf",
  "tags": [
    "JavaScript"
  ],
  "speakers": {
    "total": 19,
    "womenAndNonBinary": 8
  },
  "organizer": {
    "name": "BeJS"
  }
}

=== beerose/diversity.lol/src/data/conferences/react-summit-us.json
{
	"$schema": "../../../public/schema/v1.json",
	"name": "React Summit US",
	"description": "The biggest React conference – React Summit – comes to the USA.",
	"startDate": "2023-11-13",
	"location": "New York, USA",
	"url": "https://reactsummit.us/",
	"tags": ["JavaScript", "React", "React Native"],
	"speakers": {
		"total": 52,
		"womenAndNonBinary": 14
	},
	"organizer": {
		"name": "GitNation",
		"url": "https://gitnation.org/",
		"forProfit": true
	}
}

=== beerose/diversity.lol/src/data/conferences/ng-belgrade.json
{
	"$schema": "../../../public/schema/v1.json",
	"name": "NG Belgrade Conf",
	"description": "NG Belgrade Conf 2024 is the largest Angular conference in the Balkans.",
	"startDate": "2023-11-4",
	"location": "Belgrade, Serbia",
	"url": "https://angularbelgrade.org/",
	"tags": ["JavaScript", "Angular"],
	"speakers": {
		"total": 7,
		"womenAndNonBinary": 1
	},
	"organizer": {
		"name": "Angular Belgrade"
	}
}

=== beerose/diversity.lol/src/data/conferences/reactparis.json
{
	"$schema": "../../../public/schema/v1.json",
	"name": "React Paris 2024",
	"description": "A family-like, community-run JavaScript Conference!",
	"startDate": "2024-03-22",
	"location": "Paris, France",
	"url": "https://react.paris/",
	"tags": ["JavaScript", "React"],
	"speakers": {
		"total": 13,
		"womenAndNonBinary": 6
	},
	"organizer": {
		"name": "BeJS"
	}
}

=== beerose/diversity.lol/src/data/conferences/reactjsday-it.json
{
	"$schema": "../../../public/schema/v1.json",
	"name": "reactjsday",
	"description": "reactjsday is proudly organised by GrUSP.",
	"startDate": "2023-10-27",
	"location": "Verona, Italy",
	"url": "https://reactjsday.it/",
	"tags": ["JavaScript", "React"],
	"speakers": {
		"total": 10,
		"womenAndNonBinary": 3
	},
	"organizer": {
		"name": "GrUSP",
		"forProfit": false,
		"url": "https://grusp.org"
	}
}

=== beerose/diversity.lol/src/data/conferences/jsconf-colombia.json
{
	"$schema": "../../../public/schema/v1.json",
	"name": "JSConf Colombia",
	"description": "JSConf Colombia is not just a conference; it's a celebration. One that is a testament to the power of unity, knowledge, and passion. So, let's make this farewell party unforgettable.",
	"startDate": "2023-11-17",
	"location": "Medell√≠n, Colombia",
	"url": "https://www.jsconf.co/",
	"tags": ["JavaScript"],
	"speakers": {
		"total": 25,
		"womenAndNonBinary": 7
	},
	"organizer": {
		"name": "JSConf Colombia Crew"
	}
}
