=== beerose/diversity.lol/public/schema/v1.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Conference",
	"description": "A conference",
	"type": "object",
	"additionalProperties": false,
	"required": ["name", "description", "startDate", "tags", "location", "url", "speakers"],
	"properties": {
		"$schema": {
			"type": "string"
		},
		"name": {
			"description": "The name of the conference",
			"type": "string"
		},
		"description": {
			"description": "More information about the conference",
			"type": "string"
		},
		"startDate": {
			"description": "The start date of the conference (YYYY-MM-DD)",
			"type": "string"
		},
		"cfp": {
			"description": "The CFP open and close dates of the conference (YYYY-MM-DD)",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"open": {
					"description": "The CFP open date of the conference (YYYY-MM-DD)",
					"type": "string"
				},
				"close": {
					"description": "The CFP close date of the conference (YYYY-MM-DD)",
					"type": "string"
				},
				"url": {
					"description": "The CFP URL of the conference",
					"type": "string"
				}
			}
		},
		"status": {
			"description": "The status of the conference",
			"type": "string",
			"enum": ["cfp open", "cfp closed"]
		},
		"tags": {
			"description": "The tags of the conference",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"location": {
			"description": "The location of the conference",
			"type": "string"
		},
		"url": {
			"description": "The URL of the conference",
			"type": "string"
		},
		"social": {
			"description": "The social media of the conference",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"twitter": {
					"description": "The Twitter handle of the conference",
					"type": "string"
				}
			}
		},
		"organizer": {
			"description": "The organizer of the conference",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"description": "The name of the organizer",
					"type": "string"
				},
				"url": {
					"description": "The URL of the organizer",
					"type": "string"
				},
				"forProfit": {
					"description": "Whether the organizer is for-profit",
					"type": "boolean"
				}
			}
		},
		"size": {
			"description": "The size of the conference",
			"type": "string"
		},
		"speakers": {
			"description": "The speakers of the conference",
			"type": "object",
			"additionalProperties": false,
			"required": ["total", "womenAndNonBinary"],
			"properties": {
				"total": {
					"description": "The total number of speakers",
					"type": "number"
				},
				"womenAndNonBinary": {
					"description": "The number of women and non-binary speakers",
					"type": "number"
				},
				"womenAndNonBinaryMain": {
					"description": "The number of women and non-binary speakers on the main track (if there is one)",
					"type": "number"
				}
			}
		}
	}
}

=== beerose/diversity.lol/data/conferences/nodeconf-eu.json
{
  "$schema": "../../public/schema/v1.json",
  "name": "React Day Berlin 2023",
  "description": "NodeConf EU brings together the brightest minds in the Node.js community.",
  "startDate": "2023-11-06",
  "location": "Kilkenny, Ireland",
  "url": "https://testjssummit.com/",
  "tags": ["JavaScript", "Testing"],
  "speakers": {
    "total": 38,
    "womenAndNonBinary": 5
  },
  "organizer": {
    "name": "NearForm",
    "url": "https://www.nearform.com/",
    "forProfit": true
  },
  "social": {
    "twitter": "NodeConfEU"
  }
}

=== beerose/diversity.lol/src/data/conferences/reactbrussels.json
{
	"$schema": "../../../public/schema/v1.json",
	"name": "React Brussels 2023",
	"description": "A family-like, community-run JavaScript Conference!",
	"startDate": "2023-05-12",
	"location": "Brussels, Belgium",
	"url": "https://www.react.brussels/",
	"tags": ["JavaScript"],
	"speakers": {
		"total": 16,
		"womenAndNonBinary": 7
	},
	"organizer": {
		"name": "BeJS"
	}
}
